### PR TITLE
Issue8

### LINKED ISSUE #8: Add support for `__gap`
`__gap`s can be processed after the layouts are overlayed and aligned.

**Edit:** See 'Update' at the end for easier approach! 👇

<br>

**How to do this:**

Let's say that we have a contract X.

This is its storage layout:

```
x1
x2
__gap [10]
```

Gaps are often used when developing upgradeable smart contracts. See OpenZeppelin's [documentation](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#storage-gaps).

Let's say we update X to look like this:

```
x1
x2
x3
x4
__gap [8]
```

*(assuming x3 and x4 occupy one slot each)*

We added two new variables (x3 and x4), and correctly shrink the gap by two (10 => 8).

However, if we run Storage Delta, these variables will be marked!

We need to identify that these variables are in the storage space previously reserved by the gap, and de-escalate the findings.
I recommend taking a look at `alignedOldVisualized` and `alignedOverlayedVisualized` JSONs to think about it.

Keep in mind that there can be multiple `__gap`s in a contract (regex: `/^__gap/`).

Additionally, we need to make sure gaps have been shrunk by the right amount.

## Update

There may be a straightforward way to solve this.
We won't be changing layout JSONs at all.

First, we determine 'gap spaces' from the old layout JSON.
For example, let's say there are gap spaces at positions `10-14` and `24-26`.
Thats's 2 gap spaces of sizes 4 and 2. We record this for future reference.

The first rule is to de-escalate findings for variables in a gap space.
For example, 🏴 becomes 🌱, and so on.
This can be done by always asking, "Is the variable in a gap space?" before we write to the report, and de-escalating if so.

The second rule is that we print an empty line to the old report for each variable that has been de-escalated.
This way our reports will remain aligned.

The third rule is to make sure that the gap space is either filled completely, or contains a gap at the end, correctly shrunk based its current position and its old position.
Gaps can be of any type, so we should use `size` to perform the check.

### PR DESCRIPTION
**Pull request by kamuik16**
## Description

Draft PR for #8 

### Additional context

I have added some initial logic to support __gap storage gaps variable.

### CODE REVIEW

**Review by ZeroEkkusu — COMMENTED** [review]
Okay, I've done some research and we're going to set one rule:

`__gap`s must be of size `32 * n`. You don't need to worry about it because it's already what we're doing.
Just a **note** to self that we may want to throw an error if that isn't the case.

---

1. We'll need `problematicOnlyBecauseOfGap` function:

IN: item from new layout, old layout
OUT: whether item from new layout overlaps only with gap from old layout

The function just needs to iterate over the items from the old layout, and using the current item's `start` and `end`, check if there's an overlap with the provided item from the new layout (by comparing to its `start` and `end`).
If there's an overlap, return `false` if the current item is not a `__gap`.
If it is a `__gap`, just continue.
Return `true` at the end, i.e., if we don't find an overlap with an item from the old layout that is not a `__gap`.

This should be straightforward to do.

<br>

Let's start from there - by adding this function. I'll continue to debug the code in the meantime.
Let me know if you think this is a good idea.

**Comment by kamuik16** [comment]
> Okay, I've done some research and we're going to set one rule:
> 
> `__gap`s must be of size `32 * n`. You don't need to worry about it because it's already what we're doing. Just a **note** to self that we may want to throw an error if that isn't the case.
> 
> 1. We'll need `problematicOnlyBecauseOfGap` function:
> 
> IN: item from new layout, old layout OUT: whether item from new layout overlaps only with gap from old layout
> 
> The function just needs to iterate over the items from the old layout, and using the current item's `start` and `end`, check if there's an overlap with the provided item from the new layout (by comparing to its `start` and `end`). If there's an overlap, return `false` if the current item is not a `__gap`. If it is a `__gap`, just continue. Return `true` at the end, i.e., if we don't find an overlap with an item from the old layout that is not a `__gap`.
> 
> This should be straightforward to do.
> 
> 
> Let's start from there - by adding this function. I'll continue to debug the code in the meantime. Let me know if you think this is a good idea.

This is the same as `variableFitInGap` function, isn't it?

**Comment by ZeroEkkusu** [comment]
It's another, separate function.

`variableFitInGap` check's if the variable fits in the gap wholly. That is to say, it starts and ends in the gap.

`problematicOnlyBecauseOfGap` checks for a partial overlap, and we'll use it to cover an edge case later.

Here's an example:

`var` starts at position `0`.
`gap` starts at position `1`.

```
0   var
1   gap
```

Let's say that we change the type of `var` to a type that occupies more space.

`var` starts at position `0`, but is of a bigger type and occupies position `1` as well.
`gap` now starts at position `2`.

```
0   biggerVar
2   gap
```

If you think about it, `var` now occupies both the space that it previously occupied (`0`) AND some space that the `gap` used to occupy (`1`).

We'll need a function to check for that, and that's why we're adding it.

Let me know if that makes sense.

**Comment by kamuik16** [comment]
> It's another, separate function.
> 
> `variableFitInGap` check's if the variable fits in the gap wholly. That is to say, it starts and ends in the gap.
> 
> `problematicOnlyBecauseOfGap` checks for a partial overlap, and we'll use it to cover an edge case later.

I think it's probably good if you take it on from here, because you will have to explain each and everything and it will consume your much of time so maybe I'll close this PR and let you do your job. What do you think?

**Comment by ZeroEkkusu** [comment]
Whatever you prefer. I have something else to work on, so I won't get back to Storage Delta this week. Totally fine if you want or not want to give it a shot in the meantime.

**Comment by kamuik16** [comment]
> Whatever you prefer. I have something else to work on, so I won't get back to Storage Delta this week. Totally fine if you want or not want to give it a shot in the meantime.

Okay @ZeroEkkusu! Btw it was great doing discussion with you on this and I definitely learned a lot! Thanks! Closing this PR.

**Comment by ZeroEkkusu** [comment]
Thank you,
Take care, @kamuik16!

**Pull request closed without merging**
